name: test-build-staging
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Access API_URL
        env:
          API_URL: "https://staging.logora.fr/api/v1"
        run: echo API_URL=\"$API_URL\" > ./local.properties
      - name: Clean
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew assembleDebug
